services:
  mis_sb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mis_sb
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mis_sb_db
      DB_PORT: 3306
      DB_DATABASE: backend
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/app
    depends_on:
      - mis_sb_db
    command: ["apache2-foreground"]

  mis_sb_db:
    image: mysql
    container_name: mis_sb_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
